/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '17-5-16 下午5:09' with Gradle 3.2.1
 *
 * @author Administrator, @date 17-5-16 下午5:09
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
